name: Python Application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Define a versão do Python que você quer usar

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run script
      run: |
        python script.py

    - name: List files
      run: |
        ls -la
